export default [
  {
    id: 0,
    name: "Useless Sprocket",
    description: "A toothed wheel with several teeth missing or bent",
    material: "steel",
    meltable: true,
    meltvalue: 2,
  },
  {
    id: 1,
    name: "Doohickey Case",
    description: "A little metal box that used to contain some kind of device",
    material: "steel",
    meltable: true,
    meltvalue: 1,
  },
  {
    id: 2,
    name: "Dead Lightbulb",
    description: "A sooty bulb with broken filaments",
    material: "complex",
  },
  {
    id: 3,
    name: "Cracked Vial",
    description: "An acrid-smelling vial, no longer watertight",
    material: "glass",
  },
  {
    id: 4,
    name: "Table Leg",
    description: "A disembodied wooden table leg",
    material: "wood",
  },
  {
    id: 5,
    name: "Frazzled Motor",
    description: "An electric motor which has been pushed beyond its limits",
    material: "complex",
  },
  {
    id: 6,
    name: "Dog-eared Manual",
    description: "This would have been informative, but it's all soggy",
    material: "paper",
  },
  {
    id: 7,
    name: "Stripped Bolt",
    description: "A large steel bolt worn smooth",
    material: "steel",
    meltable: true,
    meltvalue: 2,
  },
  {
    id: 8,
    name: "Flanged Offcut",
    description: "A steel plate bent on one edge",
    material: "steel",
    meltable: true,
    meltvalue: 1,
  },
] as Item[];
